
    package miniprojet_duo_SANCHEZ;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class FenetrePrincipale extends javax.swing.JFrame {

    GrilleDeJeu grille;
    JButton[][] boutons;

    public FenetrePrincipale() {
        initComponents(); // Méthode générée par NetBeans, ne pas modifier.
        
        int nbLignes = 10;
        int nbColonnes = 10;
        int nbBombes = 20; // Nombre de bombes par défaut

        // Initialisation des éléments de la grille de jeu
        grille = new GrilleDeJeu(nbLignes, nbColonnes, nbBombes);
        boutons = new JButton[nbLignes][nbColonnes];

        // Configure le panneau après l'initialisation
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));

        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                JButton bouton_cellule = new JButton();
                boutons[i][j] = bouton_cellule;
                PanneauGrille.add(bouton_cellule);

                int ligne = i;
                int colonne = j;

                bouton_cellule.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        revelerCellule(ligne, colonne);
                    }
                });
            }
        }

        pack(); // Ajuste la taille de la fenêtre après avoir ajouté les composants
    }

    private void revelerCellule(int ligne, int colonne) {
        if (grille.getCellule(ligne, colonne).estDevoilee()) {
            return;
        }

        grille.revelerCellule(ligne, colonne);
        mettreAJourBoutons();

        if (grille.getCellule(ligne, colonne).getPresenceBombe()) {
            JOptionPane.showMessageDialog(this, "Vous avez touché une bombe ! La partie est terminée.", "Perdu", JOptionPane.ERROR_MESSAGE);
            desactiverBoutons();
        } else if (grille.estPartieTerminee()) {
            JOptionPane.showMessageDialog(this, "Félicitations ! Vous avez gagné.", "Gagné", JOptionPane.INFORMATION_MESSAGE);
            desactiverBoutons();
        }
    }

    private void mettreAJourBoutons() {
        for (int i = 0; i < grille.getNbLignes(); i++) {
            for (int j = 0; j < grille.getNbColonnes(); j++) {
                Cellule cellule = grille.getCellule(i, j);
                JButton bouton = boutons[i][j];

                if (cellule.estDevoilee()) {
                    bouton.setEnabled(false);
                    if (cellule.getPresenceBombe()) {
                        bouton.setText("B");
                    } else {
                        int nbBombesAdjacentes = cellule.getNbBombesAdjacentes();
                        bouton.setText(nbBombesAdjacentes > 0 ? String.valueOf(nbBombesAdjacentes) : "");
                    }
                }
            }
        }
    }

    private void desactiverBoutons() {
        for (int i = 0; i < grille.getNbLignes(); i++) {
            for (int j = 0; j < grille.getNbColonnes(); j++) {
                boutons[i][j].setEnabled(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(255, 0, 0));
        PanneauGrille.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanneauGrille.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    // End of variables declaration//GEN-END:variables
}
